exports.phrases = [
  `"Buy Zcash for financial freedom"`,
  `"Bought your entire family's networth x 10"`,
  `"Sold my House for Zcash"`,
  `"Zcash Flippening > $ETH Flippening"`,
  `"All in Zcash or get liquidated trying"`,
  `"I have more Zcash than your country"`,
  `"Target sir? 1 $ZEC = 7 $BTC - tm3k"`,
  `"Running Zcash - Zooko"`,
  `"Wait for the dip and go all in"`,
  `"Slap yourself if you ever sold ZEC"`,
  `"Buying more anyways. fuck you bears. - Aabtc"`,
  `"Buy $ZEC at $50, Sell at $500 - Anondran"`,
  `"Private economic intercourse"`,
  `"Load Z Pump.exe"`,
  `"33k by July"`,
  `"Zcash Halving is not priced in"`,
  `"Zcash is privacy, privacy is freedom, freedom is power - tm3k"`,
  `"Enter all Zcash markets"`,
];